-keep class org.apache.commons.compress.** { *; }
-dontwarn org.apache.commons.compress.**
-keepattributes Signature
-keep class org.apache.commons.compress.archivers.zip.** { *; }
-optimizationpasses 7